### ISSUE TITLE
Calling `serializeUpdateContractParameters` with wrong receive name returns empty buffer

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-node-sdk-js#116]
**Bug Description**

As stated, calling `serializeUpdateContractParameters` with a wrong `receiveName` returns and empty buffer instead of an error.

**Steps to Reproduce**

- Call `serializeUpdateContractParameters` with a receive name that is not included in the schema given to the function

**Expected Result**
- Throws an error

**Actual Result**
- Returns empty buffer

**Versions**
- Software Version: common-sdk 6.2

**Comment by soerenbf** [comment]
This behavior also happens when you call the function with a parameter of the wrong format. It would be nice with proper error messages, as it's hard to debug what is wrong otherwise.

**Comment by abizjak** [comment]
The problem here, and not just here, is that `Buffer.from` does no validation. So basically `serializeUpdateContractParameters` never fails. The Rust function does fail, but then the error is never propagated

This
```
    try {
        return Buffer.from(serializedParameters, 'hex');
    } catch (e) {
        throw new Error(
            'unable to deserialize parameters, due to: ' + serializedParameters
        ); // In this case serializedParameters is the error message from the rust module
    }
```

Never goes into the exception handling branch since `Buffer.from` will just consume the amount of
